# Generated by Django 4.1.3 on 2022-12-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersclub',
            name='club_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
