# Generated by Django 4.1.3 on 2022-12-14 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_usersocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialmedia',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to=settings.AUTH_USER_MODEL),
        ),
    ]
